#!/bin/bash
# My first script

sudo php app/console doctrine:schema:update --force
sudo php app/console cache:clear --no-optional-warmers --env=prod
sudo php app/console cache:clear --no-optional-warmers --env=dev
sudo chgrp www-data ./ -R
sudo chmod g+w ./ -R
