imports:
    - { resource: config.yml }

#framework:
#    validation:
#        cache: apc

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

monolog:
#    handlers:
#        main:
#            type:         fingers_crossed
#            action_level: debug
#            handler:      nested
#        nested:
#            type:  stream
#            path:  "%kernel.logs_dir%/%kernel.environment%.log"
#            level: debug
#        console:
#            type:  console
    handlers:
        main:
            type:   stream
            path:   "%kernel.logs_dir%/%kernel.environment%.log"
            level:  debug
        console:
            type:   console
            bubble: false
        request:
            type:   stream
            path:   "%kernel.logs_dir%/request.log"
            channels: [request]
        security:
            type:   stream
            path:   "%kernel.logs_dir%/security.log"
            channels: [security]
