imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: settings.yml }
    - { resource: @DarkishCategoryBundle/Resources/config/admin.yml }

framework:
    #esi:             ~
    #translator:      { fallback: "%locale%" }
    translator: ~
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig', 'php']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    form:
        resources:
            - BraincraftedBootstrapBundle:Form:bootstrap.html.twig
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles: [ "FOSCommentBundle" ]    
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        types:
            phone_number: Misd\PhoneNumberBundle\Doctrine\DBAL\Types\PhoneNumberType
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: "%kernel.root_dir%/data/data.db3"
        # path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        entity_managers:
            default:
                auto_mapping: true
                mappings: ~


# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }


services:
    my.subscriber:
        class: Darkish\CategoryBundle\EventListener\TreeSubscriber
        tags:
            - { name: doctrine.event_subscriber, connection: default }
    my_user.manager:
        class: Darkish\UserBundle\EventListener\UserManager
        arguments:
            - @security.encoder_factory
        tags:
            - { name: doctrine.event_subscriber, connection: default }
    my_comment.subscriber:
        class: Darkish\CommentBundle\EventListener\CommentSubscriber
        tags:
            - { name: doctrine.event_subscriber, connection: default}
        arguments: ["@service_container", "%darkish.comment%"]
    my_mencryptor:
        class: Darkish\WebsiteBundle\Security\Mencryptor



# app/config/config.yml
knp_menu:
    # use "twig: false" to disable the Twig extension and the TwigRenderer
    twig:
        template: knp_menu.html.twig
    #  if true, enables the helper for PHP templates
    templating: true
    # the renderer to use, list is also available by default
    default_renderer: twig
    
liip_imagine:
    resolvers:
       default:
          web_path: ~

    filter_sets:
        cache: ~
        my_thumb:
            quality: 60
            filters:
                thumbnail: {size: [320, 180], mode: outbound }
        web_thumb:
            quality: 60
            filters:
                thumbnail: { size: [1280, 960], mode: inset }
#                custom_watermark: {}

        mobile_thumb:
            quality: 60
            filters:
                thumbnail: { size: [640, 480], mode: inset }
#                watermark:
#                    # Relative path to the watermark file (prepended with "%kernel.root_dir%/")
#                    image: Resources/data/watermark.png
#                    # Size of the watermark relative to the origin images size
#                    size: 0.5
#                    # Position: One of topleft,top,topright,left,center,right,bottomleft,bottom,bottomright
#                    position: topright
        icon_thumb:
            quality: 60
            filters:
                thumbnail: { size: [128, 128], mode: outbound }
#                watermark:
#                    # Relative path to the watermark file (prepended with "%kernel.root_dir%/")
#                    image: Resources/data/watermark.png
#                    # Size of the watermark relative to the origin images size
#                    size: 0.5
#                    # Position: One of topleft,top,topright,left,center,right,bottomleft,bottom,bottomright
#                    position: topright
        64:
            filters:
                relative_resize: { widen: 64 }
        128:
            filters:
                relative_resize: { widen: 128 }
        256:
            filters:
                relative_resize: { widen: 256 }
#                watermark:
#                    # Relative path to the watermark file (prepended with "%kernel.root_dir%/")
#                    image: Resources/data/watermark.png
#                    # Position: One of topleft,top,topright,left,center,right,bottomleft,bottom,bottomright
#                    position: topright
        512:
            filters:
                relative_resize: { widen: 512 }
#                watermark:
#                    # Relative path to the watermark file (prepended with "%kernel.root_dir%/")
#                    image: Resources/data/watermark.png
#                    # Position: One of topleft,top,topright,left,center,right,bottomleft,bottom,bottomright
#                    position: topright
        1024:
            filters:
                relative_resize: { widen: 1024 }
#                watermark:
#                    # Relative path to the watermark file (prepended with "%kernel.root_dir%/")
#                    image: Resources/data/watermark.png
#                    # Position: One of topleft,top,topright,left,center,right,bottomleft,bottom,bottomright
#                    position: topright

        240x200:
            filters:
                upscale: { min: [240,200] }
                thumbnail: { size: [240,200], mode: outbound }

        300x200:
            filters:
                upscale: { min: [300,200] }
                thumbnail: { size: [300,200], mode: outbound }


        240x200default:
            filters:
                background: { size: [240, 200], color: '#eee' }
#                watermark:
#                  image: Resources/data/watermark.png
#                  position: center

        1024x576:
            filters:
                upscale: { min: [1024,576] }
                thumbnail: { size: [1024,576], mode: outbound }
        180x120:
            filters:
                upscale: { min: [180,120] }
                thumbnail: { size: [180,120], mode: outbound }

        84x56:
            filters:
                upscale: { min: [84,56] }
                thumbnail: { size: [84,56], mode: outbound }

dubture_f_fmpeg:
    ffmpeg_binary: ffmpeg
    ffprobe_binary: ffprobe
    binary_timeout: 0
    threads_count: 4

oodle_krumo:
    skin:
        selected: schabalon.com
    css:
        url: /krumo/
    display:
        show_version: true
        show_call_info: true
        cascade: [5,10]

fos_comment:
    db_driver: orm
    class:
        model:
            comment: Darkish\CommentBundle\Entity\Comment
            thread: Darkish\CommentBundle\Entity\Thread

# jms_serializer:
#     metadata:
#         directories:
#             FOSCB:
#                 namespace_prefix: "FOS\\CommentBundle"
#                 path: "%kernel.root_dir%/Resources/serializer/FOSCB"

sensio_framework_extra:
    request: { converters: true }


fos_rest:
    body_converter:
        enabled: true
    disable_csrf_role: ROLE_API
    param_fetcher_listener: true
    view:
        mime_types:
            json: ['application/json', 'application/json;version=1.0', 'application/json;version=1.1']
        view_response_listener: 'force'
        formats:
            json: true
        templating_formats:
            html: true
    format_listener:
        rules:
            - { path: ^/, priorities: [ html, json, xml ], fallback_format: ~, prefer_extension: true }
        media_type:
            version_regex: '/(v|version)=(?P<version>[0-9\.]+)/'
    exception:
        codes:
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': 404
            'Doctrine\ORM\OptimisticLockException': HTTP_CONFLICT
        messages:
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': true
    allowed_methods_listener: true
    access_denied_listener:
        json: true
    body_listener: true


# fos_rest:
#     body_converter:
#         enabled: true
#     param_fetcher_listener: true
#     body_listener: true
#     format_listener: true
#     disable_csrf_role: ROLE_API
#     view:
#         formats:
#             rss: true
#             xml: false
#             json: true
#         templating_formats:
#             html: true
#         force_redirects:
#             html: true
#         failed_validation: HTTP_BAD_REQUEST
#         default_engine: twig
#         view_response_listener: 'force'
#         exception_wrapper_handler:  null

#     routing_loader:
#         default_format: json
#     exception:
#         enabled: true
#     service:
#         exception_handler:    fos_rest.view.exception_wrapper_handler


nelmio_api_doc: ~

pierrre_encrypter:
    encrypters: #Encrypters list, requires at least one encrypter.
        my_encrypter: #Encrypter name
            key: "@kernel.secret" #The secret that is used to encrypt data. By default, it will use the kernel secret.
            algorithm: "rijndael-128" #Encryption algorithm
            mode: "cbc" #Encryption mode
            random_initialization_vector: true #If you set it to false, it will use a blank string as initialization vector.
            base64: true #Encode the encrypted data with the base64 algorithm.
            base64_url_safe: true #Replace "+" and "/" characters by "-" and "_".
    twig: #Twig extension
        enabled: false #Enable extension
        default_encrypter: null #Default encrypter. By default, it's the first encrypter

nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: []
        allow_headers: []
        allow_methods: []
        expose_headers: []
        max_age: 0
        hosts: []
        origin_regex: false
    paths:
        '^/api/':
            allow_origin: ['*']
            allow_headers: ['X-Custom-Auth']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
            max_age: 3600
        '^/_uploader/image/upload/':
            allow_origin: ['*']
            allow_headers: ['X-Custom-Auth']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
            max_age: 3600
        '^/':
            origin_regex: true
            allow_origin: ['^http://localhost:[0-9]+']
            allow_headers: ['X-Custom-Auth']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
            max_age: 3600
            hosts: ['^api\.']

knp_snappy:
    pdf:
        enabled:    true
        binary:     /usr/local/bin/wkhtmltopdf
        options:    []
    image:
        enabled:    true
        binary:     /usr/local/bin/wkhtmltoimage
        options:    []


braincrafted_bootstrap:
    output_dir:
    assets_dir: %kernel.root_dir%/../vendor/twbs/bootstrap
    jquery_path: %kernel.root_dir%/../vendor/jquery/jquery/jquery-1.10.2.js
    less_filter: less # "less", "lessphp", "sass" or "none"
    fonts_dir: %kernel.root_dir%/../web/fonts
    auto_configure:
        assetic: false
        twig: true
        knp_menu: true
        knp_paginator: true
    customize:
        variables_file: ~
        bootstrap_output: %kernel.root_dir%/Resources/less/bootstrap.less
        bootstrap_template: BraincraftedBootstrapBundle:Bootstrap:bootstrap.less.twig


sonata_block:
    default_contexts: [sonata_page_bundle]
    blocks:
        sonata.admin.block.admin_list:
            contexts:   [admin]

        #sonata.admin_doctrine_orm.block.audit:
        #    contexts:   [admin]

        sonata.block.service.text:
        darkish_website.block.rss: ~
        darkish_website.block.offer: ~
        darkish_website.block.weather: ~
        darkish_website.block.comment: ~
        darkish_website.block.database: ~
        darkish_website.block.centers: ~
        darkish_website.block.sponsors: ~



        # Some specific block from the SonataMediaBundle
        #sonata.media.block.media:
        #sonata.media.block.gallery:
        #sonata.media.block.feature_media:

sonata_admin:
    title:      پنل درکیش
    title_logo: bundles/acmedemo/img/fancy_acme_logo.png

gregwar_captcha: ~

knp_paginator:
    page_range: 5                      # default page range used in pagination control
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: direction # sort direction query parameter name
        distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
        pagination: KnpPaginatorBundle:Pagination:twitter_bootstrap_v3_pagination.html.twig     # sliding pagination controls template
        sortable: KnpPaginatorBundle:Pagination:sortable_link.html.twig # sort link template

white_october_breadcrumbs: 
    separator:          '<i class="fa fa-long-arrow-left"></i>'
    separatorClass:     'separator'
    listId:             'wo-breadcrumbs'
    listClass:          'breadcrumb'
    itemClass:          ''
    linkRel:            ''
    locale:             ~ # defaults to null, so the default locale is used
    translation_domain: ~ # defaults to null, so the default domain is used
    viewTemplate:       'DarkishWebsiteBundle:Breadcrumbs:breadcrumbs.html.twig'


oneup_uploader:
    mappings:
        image:
            frontend: plupload
            use_orphanage: true
            namer: darkish_website.uploader_namer
            storage:
                directory:            uploads/image
    orphanage:
        maxage: 86400
        directory: %kernel.root_dir%/../web/uploader/cache
