darkish_website:
    resource: "@DarkishWebsiteBundle/Resources/config/routing.yml"
    prefix:   /

darkish_comment:
    resource: "@DarkishCommentBundle/Controller/"
    type:     annotation
    prefix:   /

darkish_customer:
    resource: "@DarkishCustomerBundle/Controller/"
    type:     annotation
    prefix:   /


darkish_panel:
    resource: "@DarkishPanelBundle/Resources/config/routing.yml"
    prefix:   /

darkish_category:
    resource: "@DarkishCategoryBundle/Resources/config/routing.yml"
    prefix:   /




fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
    
darkish_api:
    resource: "Darkish\UserBundle\Controller\ApiController"
    type:     rest
    prefix:   api/rest

darkish_api_message:
    resource: "Darkish\UserBundle\Controller\ApiMessageController"
    type:     rest
    prefix:   api/rest/message

darkish_api_comment:
    resource: "Darkish\UserBundle\Controller\ApiCommentController"
    type:     rest
    prefix:   api/rest/comment

darkish_api_itinerary:
    resource: "Darkish\UserBundle\Controller\ApiItineraryController"
    type:     rest
    prefix:   api/rest/itinerary

darkish_api_cno:
    resource: "Darkish\UserBundle\Controller\ApiCnoController"
    type:     rest
    prefix:   api/rest/cno

darkish_api_store:
    resource: "Darkish\UserBundle\Controller\ApiStoreController"
    type:     rest
    prefix:   api/rest/store

darkish_api_database:
    resource: "Darkish\UserBundle\Controller\ApiDatabaseController"
    type:     rest
    prefix:   api/rest/database

darkish_user:
    resource: "Darkish\UserBundle\Controller\OperatorController"
    type:     annotation
    prefix:   /
    
_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

KrumoBundle:
    resource: "@OodleKrumoBundle/Resources/config/routing/routing.yml"
    prefix:   /    


fos_comment_api:
    type: rest
    resource: "@FOSCommentBundle/Resources/config/routing.yml"
    prefix: /api
    defaults: { _format: html }

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin/panel

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin/panel

oneup_uploader:
    resource: .
    type: uploader