darkish_comment:
    resource: "@DarkishCommentBundle/Controller/"
    type:     annotation
    prefix:   /

darkish_customer:
    resource: "@DarkishCustomerBundle/Controller/"
    type:     annotation
    prefix:   /


darkish_panel:
    resource: "@DarkishPanelBundle/Resources/config/routing.yml"
    prefix:   /

darkish_category:
    resource: "@DarkishCategoryBundle/Resources/config/routing.yml"
    prefix:   /




fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
    
darkish_api:
    resource: "Darkish\UserBundle\Controller\ApiController"
    type:     rest
    prefix:   api/rest

darkish_user:
    resource: "@DarkishUserBundle/Controller/"
    type:     annotation
    prefix:   /
    
_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

KrumoBundle:
    resource: "@OodleKrumoBundle/Resources/config/routing/routing.yml"
    prefix:   /    


fos_comment_api:
    type: rest
    resource: "@FOSCommentBundle/Resources/config/routing.yml"
    prefix: /api
    defaults: { _format: html }

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc