darkish_customer:
    resource: "@DarkishCustomerBundle/Controller/"
    type:     annotation
    prefix:   /


darkish_panel:
    resource: "@DarkishPanelBundle/Resources/config/routing.yml"
    prefix:   /

darkish_category:
    resource: "@DarkishCategoryBundle/Resources/config/routing.yml"
    prefix:   /




fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
    
darkish_user:
    resource: "@DarkishUserBundle/Controller/"
    type:     annotation
    prefix:   /
    
_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"