<?php

namespace Darkish\CategoryBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MainTreeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MainTreeRepository extends EntityRepository
{
}
