<?php

namespace Darkish\CategoryBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Darkish\CategoryBundle\Entity\MainTree;

/**
 * RecordRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecordRepository extends EntityRepository
{
	public function getRecordsForCat(MainTree $tree) {
        $mainTreeRepo = $this->getEntityManager()->getRepository('DarkishCategoryBundle:MainTree');

        $children = $mainTreeRepo->getTreeChildren($tree);

        $treesIds = array();
        $treesIds[] = $tree->getId();
        foreach($children as $child) {
            $treesIds[] = $child->getId();
        }

        $recordQuery = $this->createQueryBuilder('r');
        $recordQuery->join('r.maintrees', 'rt');
        $recordQuery->join('rt.tree','t', 'WITH',$recordQuery->expr()->in('t.id', $treesIds))->distinct();
        $recordQuery->orderBy('r.lastUpdate', 'Desc');
        // $recordQuery->addOrderBy('nt.sort', 'Asc');

        return $recordQuery;
    }
}
