parameters:
#    darkish_panel.example.class: Darkish\PanelBundle\Example

services:
#    darkish_panel.example:
#        class: %darkish_panel.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
