darkish_website:
    resource: "Darkish\WebsiteBundle\Controller\DefaultController"
    type:     annotation
    prefix:   /
darkish_website_record_request:
    resource: "Darkish\WebsiteBundle\Controller\RecordRequestController"
    type:     annotation
    prefix:   /
darkish_website_customer_remember_password:
    resource: "Darkish\WebsiteBundle\Controller\CustomerPasswordRequestController"
    type:     annotation
    prefix:   /password/customer
