services:
#    darkish_website.example:
#        class: Darkish\WebsiteBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    website.menu_builder:
        class: Darkish\WebsiteBundle\Menu\WebsiteMenuBuilder
        arguments: ["@knp_menu.factory"]

    website.main_menu:
        class: Knp\Menu\MenuItem # the service definition requires setting the class
        factory_service: website.menu_builder
        factory_method: createMainMenu
        arguments: ["@request_stack"]
        tags:
            - { name: knp_menu.menu, alias: website_main } # The alias is what is used to retrieve the menu
    website.secondary_menu:
        class: Knp\Menu\MenuItem # the service definition requires setting the class
        factory_service: website.menu_builder
        factory_method: createSecondaryMenu
        arguments: ["@request_stack"]
        tags:
            - { name: knp_menu.menu, alias: website_secondary } # The alias is what is used to retrieve the menu
    website.third_menu:
        class: Knp\Menu\MenuItem # the service definition requires setting the class
        factory_service: website.menu_builder
        factory_method: createThirdMenu
        arguments: ["@request_stack"]
        tags:
            - { name: knp_menu.menu, alias: website_third } # The alias is what is used to retrieve the menu
    darkish_website.block.rss:
        class: Darkish\WebsiteBundle\Block\NewsBlock
        arguments:
            - "darkish_website.block.rss"
            - "@templating"
            - "@doctrine.orm.entity_manager"
        tags:
            - {name: "sonata.block"}
    darkish_website.block.centers:
        class: Darkish\WebsiteBundle\Block\CentersBlock
        arguments:
            - "darkish_website.block.centers"
            - "@templating"
            - "@doctrine.orm.entity_manager"
        tags:
            - {name: "sonata.block"}
    darkish_website.block.sponsors:
        class: Darkish\WebsiteBundle\Block\SponsorsBlock
        arguments:
            - "darkish_website.block.sponsors"
            - "@templating"
            - "@doctrine.orm.entity_manager"
            - "@service_container"
        tags:
            - {name: "sonata.block"}
    darkish_website.block.comment:
        class: Darkish\WebsiteBundle\Block\CommentsBlock
        arguments:
            - "darkish_website.block.comment"
            - "@templating"
            - "@service_container"
        tags:
            - {name: "sonata.block", scope: "request" }
    darkish_website.block.database:
        class: Darkish\WebsiteBundle\Block\DatabaseBlock
        arguments:
            - "darkish_website.block.daabase"
            - "@templating"
            - "@service_container"
        tags:
            - {name: "sonata.block", scope: "request" }
    darkish_website.user_extension:
        class: Darkish\WebsiteBundle\Twig\Extension\UserExtension
        public: false
        arguments: ["@service_container"]
        tags:
            - { name: twig.extension }
    darkish_website.comment_extension:
        class: Darkish\WebsiteBundle\Twig\Extension\CommentExtension
        public: false
        arguments: ["@service_container"]
        tags:
            - { name: twig.extension }
    darkish_website.class_extension:
        class: Darkish\WebsiteBundle\Twig\Extension\ClassExtension
        public: false
        arguments: ["@service_container"]
        tags:
            - { name: twig.extension }
    darkish_website.type.entity_hidden:
        class: Darkish\WebsiteBundle\Form\Type\EntityHiddenType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type, alias: entity_hidden }

