services:
#    darkish_website.example:
#        class: Darkish\WebsiteBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    website.menu_builder:
        class: Darkish\WebsiteBundle\Menu\WebsiteMenuBuilder
        arguments: ["@knp_menu.factory"]

    website.main_menu:
        class: Knp\Menu\MenuItem # the service definition requires setting the class
        factory_service: website.menu_builder
        factory_method: createMainMenu
        arguments: ["@request_stack"]
        tags:
            - { name: knp_menu.menu, alias: website_main } # The alias is what is used to retrieve the menu
    darkish_website.block.rss:
        class: Darkish\WebsiteBundle\Block\NewsBlock
        arguments:
            - "darkish_website.block.rss"
            - "@templating"
            - "@doctrine.orm.entity_manager"
        tags:
            - {name: "sonata.block"}

