managedfile:
    path:     /ajax/upload
    defaults: { _controller: "DarkishCategoryBundle:ManagedFile:upload" }
    requirements: { _method: post }
    

    


managedfile_gen_rand_upload_key:
    path:     /ajax/gen_rand_upload_key
    defaults: {_controller: "DarkishCategoryBundle:ManagedFile:generateRandomUploadKey"}
    requirements: { _method: get}
    
managedfile_set_temporary_tuhmbnail:
    path:     /ajax/set_temporary_thumbnail
    defaults: {_controller: "DarkishCategoryBundle:ManagedFile:setTemporaryThumbnail"}
    requirements: { _method: post}
    
    
managedfile_ffmpeg_test:
    path:     /ffmpegtest
    defaults:  { _controller: "DarkishCategoryBundle:ManagedFile:ffmpegTest"}