news:
    path:     /
    defaults: { _controller: "DarkishCategoryBundle:News:index" }

news_get_tree:
    path:     /ajax/gettree
    defaults: { _controller: "DarkishCategoryBundle:News:getTree", _format: json}

news_get_tree_linear:
    path:     /ajax/gettree_linear
    defaults: { _controller: "DarkishCategoryBundle:News:getTreeLinear", _format: json}

news_get_json:
    path:     /ajax/getjson
    defaults: { _controller: "DarkishCategoryBundle:News:getJson", _format: json}


news_get_news_for_category:
    path:     /ajax/get_news_for_cat/{cid}/{count}
    defaults: { _controller: "DarkishCategoryBundle:News:getNewsForCategory", _format: json, count: 0}

news_search_news:
    path:     /ajax/search_news/{search_by}/{sort_by}/{count}/{keyword}
    defaults: { _controller: "DarkishCategoryBundle:News:searchNewss", _format: json, keyword: "", search_by: 1, sort_by: 1}


news_verify_news:
    path:     /ajax/verify_news/{newsId}
    defaults: { _controller: "DarkishCategoryBundle:News:verifyNews", _format: json }
    requirements: { _method: post|put }

news_toggle_verify_news:
    path:     /ajax/toggle_verify_news/{newsId}
    defaults: { _controller: "DarkishCategoryBundle:News:toggleVerifyNews", _format: json }
    requirements: { _method: post|put }

news_toggle_active_news:
    path:     /ajax/toggle_active_news/{newsId}
    defaults: { _controller: "DarkishCategoryBundle:News:toggleActiveNews", _format: json }
    requirements: { _method: post|put }

news_delete_news:
    path:     /ajax/delete_news/{newsId}
    defaults: { _controller: "DarkishCategoryBundle:News:deleteNews", _format: json }
    requirements: { _method: post|put }

news_get_news:
    path:     /ajax/get_news/{id}
    defaults: { _controller: "DarkishCategoryBundle:News:getNews", _format: json}

news_get_centers:
    path:   /ajax/get_centers
    defaults: { _controller: "DarkishCategoryBundle:News:getCenters", _format: json }

news_get_safarsaz_types:
    path:   /ajax/get_safarsaz_types
    defaults: { _controller: "DarkishCategoryBundle:News:getSafarsazTypes", _format: json }

news_get_dbase_types:
    path:   /ajax/get_dbase_types
    defaults: { _controller: "DarkishCategoryBundle:News:getDbaseTypes", _format: json }

news_get_areas:
    path:   /ajax/get_areas
    defaults: { _controller: "DarkishCategoryBundle:News:getAreas", _format: json }

news_update:
    path:     ajax/{id}/update
    defaults: { _controller: "DarkishCategoryBundle:News:update" }
    requirements: { _method: post|put }

news_create:
    path:     ajax/create
    defaults: { _controller: "DarkishCategoryBundle:News:create" }
    requirements: { _method: post }

news_get_generate_csrf:
    path:     /ajax/generate_csrf
    defaults: {_controller: "DarkishCategoryBundle:News:generateCsrf", _format: json}

news_contains_tree:
    path:     /ajax/contains_tree/{newsId}/{treeId}
    defaults: { _controller: "DarkishCategoryBundle:News:containsTree", _format: json}

news_access_test:
    path:     /ajax/access
    defaults: { _controller: "DarkishCategoryBundle:News:access", _format: json}

news_get_username:
    path:     /ajax/get_username
    defaults: { _controller: "DarkishCategoryBundle:News:getUsername", _format: json}

news_get_last_newsnumber:
    path:     /ajax/get_last_newsnumber
    defaults: { _controller: "DarkishCategoryBundle:News:getLastNewsNumber", _format: json}

news_lock_news_number:
    path:     /ajax/lock_news_number/{newsNumber}
    defaults: { _controller: "DarkishCategoryBundle:News:lockNewsNumber", _format: json}
    requirements: { _method: post|put }


news_check_permission:
    path:     /ajax/check_permission/{attribute}/{id}
    defaults: { _controller: "DarkishCategoryBundle:News:checkPermission", _format: json, id: null}
    
news_get_by_id:
    path:     /ajax/get_news_by_id/{id}
    defaults: { _controller: "DarkishCategoryBundle:News:getNewsById", _format: json}
    
news_get_tree_by_index:
    path:     /ajax/get_tree_by_index/{index}
    defaults: { _controller: "DarkishCategoryBundle:News:getTreeByIndex", _format: json}
    
news_get_test_tree:
    path:     /get_test_tree/{id}
    defaults: { _controller: "DarkishCategoryBundle:News:getTestTree", _format: json}
    
news_get_total_news_for_category:
    path:     /ajax/get_total_news_for_cat/{cid}
    defaults: { _controller: "DarkishCategoryBundle:News:getTotalNewsForCategory"}
    
news_total_search_news:
    path:     /ajax/total_search_news/{search_by}/{sort_by}/{keyword}
    defaults: { _controller: "DarkishCategoryBundle:News:totalSearchNewss",  keyword: "", search_by: 1, sort_by: 1}


news_get_entities: 
    path:     /ajax/get_entity_list/{type}/{field}/{value}
    defaults: { _controller: "DarkishCategoryBundle:News:getEntityList", _format: json}