record:
    path:     /
    defaults: { _controller: "DarkishCategoryBundle:Record:index" }

record_get_tree:
    path:     /ajax/gettree
    defaults: { _controller: "DarkishCategoryBundle:Record:getTree", _format: json}

record_get_tree_linear:
    path:     /ajax/gettree_linear
    defaults: { _controller: "DarkishCategoryBundle:Record:getTreeLinear", _format: json}

record_get_json:
    path:     /ajax/getjson
    defaults: { _controller: "DarkishCategoryBundle:Record:getJson", _format: json}


record_get_record_for_category:
    path:     /ajax/get_record_for_cat/{cid}/{count}
    defaults: { _controller: "DarkishCategoryBundle:Record:getRecordForCategory", _format: json, count: 0}
    

record_search_record:
    path:     /ajax/search_record/{search_by}/{sort_by}/{count}/{keyword}
    defaults: { _controller: "DarkishCategoryBundle:Record:searchRecords", _format: json, keyword: "", search_by: 1, sort_by: 1}


record_verify_record:
    path:     /ajax/verify_record/{recordId}
    defaults: { _controller: "DarkishCategoryBundle:Record:verifyRecord", _format: json }
    requirements: { _method: post|put }

record_toggle_verify_record:
    path:     /ajax/toggle_verify_record/{recordId}
    defaults: { _controller: "DarkishCategoryBundle:Record:toggleVerifyRecord", _format: json }
    requirements: { _method: post|put }

record_toggle_active_record:
    path:     /ajax/toggle_active_record/{recordId}
    defaults: { _controller: "DarkishCategoryBundle:Record:toggleActiveRecord", _format: json }
    requirements: { _method: post|put }

record_delete_record:
    path:     /ajax/delete_record/{recordId}
    defaults: { _controller: "DarkishCategoryBundle:Record:deleteRecord", _format: json }
    requirements: { _method: post|put }

record_get_record:
    path:     /ajax/get_record/{id}
    defaults: { _controller: "DarkishCategoryBundle:Record:getRecord", _format: json}

record_get_centers:
    path:   /ajax/get_centers
    defaults: { _controller: "DarkishCategoryBundle:Record:getCenters", _format: json }

record_get_safarsaz_types:
    path:   /ajax/get_safarsaz_types
    defaults: { _controller: "DarkishCategoryBundle:Record:getSafarsazTypes", _format: json }

record_get_dbase_types:
    path:   /ajax/get_dbase_types
    defaults: { _controller: "DarkishCategoryBundle:Record:getDbaseTypes", _format: json }

record_get_areas:
    path:   /ajax/get_areas
    defaults: { _controller: "DarkishCategoryBundle:Record:getAreas", _format: json }

record_update:
    path:     ajax/{id}/update
    defaults: { _controller: "DarkishCategoryBundle:Record:update" }
    requirements: { _method: post|put }

record_create:
    path:     ajax/create
    defaults: { _controller: "DarkishCategoryBundle:Record:create" }
    requirements: { _method: post }

record_get_generate_csrf:
    path:     /ajax/generate_csrf
    defaults: {_controller: "DarkishCategoryBundle:Record:generateCsrf", _format: json}

record_contains_tree:
    path:     /ajax/contains_tree/{recordId}/{treeId}
    defaults: { _controller: "DarkishCategoryBundle:Record:containsTree", _format: json}

record_access_test:
    path:     /ajax/access
    defaults: { _controller: "DarkishCategoryBundle:Record:access", _format: json}

record_get_username:
    path:     /ajax/get_username
    defaults: { _controller: "DarkishCategoryBundle:Record:getUsername", _format: json}

record_get_last_recordnumber:
    path:     /ajax/get_last_recordnumber
    defaults: { _controller: "DarkishCategoryBundle:Record:getLastRecordNumber", _format: json}

record_lock_record_number:
    path:     /ajax/lock_record_number/{recordNumber}
    defaults: { _controller: "DarkishCategoryBundle:Record:lockRecordNumber", _format: json}
    requirements: { _method: post|put }


record_check_permission:
    path:     /ajax/check_permission/{attribute}/{id}
    defaults: { _controller: "DarkishCategoryBundle:Record:checkPermission", _format: json, id: null}
    
record_get_by_number:
    path:     /ajax/get_record_by_number/{number}
    defaults: { _controller: "DarkishCategoryBundle:Record:getRecordByNumber", _format: json}
    
record_get_tree_by_index:
    path:     /ajax/get_tree_by_index/{index}
    defaults: { _controller: "DarkishCategoryBundle:Record:getTreeByIndex", _format: json}
    
record_get_test_tree:
    path:     /get_test_tree/{id}
    defaults: { _controller: "DarkishCategoryBundle:Record:getTestTree", _format: json}
    
record_get_total_record_for_category:
    path:     /ajax/get_total_record_for_cat/{cid}
    defaults: { _controller: "DarkishCategoryBundle:Record:getTotalRecordForCategory"}
    
record_total_search_record:
    path:     /ajax/total_search_record/{search_by}/{sort_by}/{keyword}
    defaults: { _controller: "DarkishCategoryBundle:Record:totalSearchRecords",  keyword: "", search_by: 1, sort_by: 1}