record:
    path:     /
    defaults: { _controller: "DarkishCategoryBundle:Record:index" }

record_get_tree:
    path:     /ajax/gettree
    defaults: { _controller: "DarkishCategoryBundle:Record:getTree", _format: json}

record_get_tree_linear:
    path:     /ajax/gettree_linear
    defaults: { _controller: "DarkishCategoryBundle:Record:getTreeLinear", _format: json}

record_get_json:
    path:     /ajax/getjson
    defaults: { _controller: "DarkishCategoryBundle:Record:getJson", _format: json}


record_get_record_for_category:
    path:     /ajax/get_record_for_cat/{cid}/{page}
    defaults: { _controller: "DarkishCategoryBundle:Record:getRecordForCategory", _format: json, page: 1}

record_get_record:
    path:     /ajax/get_record/{id}
    defaults: { _controller: "DarkishCategoryBundle:Record:getRecord", _format: json}

record_get_centers:
    path:   /ajax/get_centers
    defaults: { _controller: "DarkishCategoryBundle:Record:getCenters", _format: json }

record_get_safarsaz_types:
    path:   /ajax/get_safarsaz_types
    defaults: { _controller: "DarkishCategoryBundle:Record:getSafarsazTypes", _format: json }

record_get_dbase_types:
    path:   /ajax/get_dbase_types
    defaults: { _controller: "DarkishCategoryBundle:Record:getDbaseTypes", _format: json }

record_get_areas:
    path:   /ajax/get_areas
    defaults: { _controller: "DarkishCategoryBundle:Record:getAreas", _format: json }

record_update:
    path:     ajax/{id}/update
    defaults: { _controller: "DarkishCategoryBundle:Record:update" }
    requirements: { _method: post|put }

record_create:
    path:     ajax/create
    defaults: { _controller: "DarkishCategoryBundle:Record:create" }
    requirements: { _method: post }

record_get_generate_csrf:
    path:     /ajax/generate_csrf
    defaults: {_controller: "DarkishCategoryBundle:Record:generateCsrf", _format: json}

record_contains_tree:
    path:     /ajax/contains_tree/{recordId}/{treeId}
    defaults: { _controller: "DarkishCategoryBundle:Record:containsTree", _format: json}

