user_logout:
    path:     /ajax/logout
    defaults: { _controller: "DarkishCategoryBundle:User:logout" }

user_is_logged_in:
    path:     /ajax/is_logged_in
    defaults: { _controller: "DarkishCategoryBundle:User:isLoggedIn" }
