services:
    client_user_provider:
        class: Darkish\UserBundle\Security\ClientUserProvider
        arguments: ["@doctrine.orm.entity_manager"]
    client_authenticator:
        class:     Darkish\UserBundle\Security\ClientAuthenticator
        arguments: ["@client_user_provider"]
    darkish.validator.valid_name:
        class:     Darkish\UserBundle\Validator\Constraints\ValidNameValidator
        arguments: ["@service_container"]
        tags:
            - { name: validator.constraint_validator, alias: darkish_valid_name }
    darkish.offline_tasks:
        class: Darkish\UserBundle\Utils\OfflineTasks
        arguments: ["@service_container"]

