<?php

namespace Proxies\__CG__\Darkish\CategoryBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class News extends \Darkish\CategoryBundle\Entity\News implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Darkish\\CategoryBundle\\Entity\\News' . "\0" . 'id', '' . "\0" . 'Darkish\\CategoryBundle\\Entity\\News' . "\0" . 'title', '' . "\0" . 'Darkish\\CategoryBundle\\Entity\\News' . "\0" . 'subTitle', '' . "\0" . 'Darkish\\CategoryBundle\\Entity\\News' . "\0" . 'createdDate', '' . "\0" . 'Darkish\\CategoryBundle\\Entity\\News' . "\0" . 'publishDate', '' . "\0" . 'Darkish\\CategoryBundle\\Entity\\News' . "\0" . 'expireDate', '' . "\0" . 'Darkish\\CategoryBundle\\Entity\\News' . "\0" . 'body', '' . "\0" . 'Darkish\\CategoryBundle\\Entity\\News' . "\0" . 'userId', '' . "\0" . 'Darkish\\CategoryBundle\\Entity\\News' . "\0" . 'status', '' . "\0" . 'Darkish\\CategoryBundle\\Entity\\News' . "\0" . 'isCompetition', '' . "\0" . 'Darkish\\CategoryBundle\\Entity\\News' . "\0" . 'trueAnswer', '' . "\0" . 'Darkish\\CategoryBundle\\Entity\\News' . "\0" . 'rate', '' . "\0" . 'Darkish\\CategoryBundle\\Entity\\News' . "\0" . 'category', '' . "\0" . 'Darkish\\CategoryBundle\\Entity\\News' . "\0" . 'newstreeId');
        }

        return array('__isInitialized__', '' . "\0" . 'Darkish\\CategoryBundle\\Entity\\News' . "\0" . 'id', '' . "\0" . 'Darkish\\CategoryBundle\\Entity\\News' . "\0" . 'title', '' . "\0" . 'Darkish\\CategoryBundle\\Entity\\News' . "\0" . 'subTitle', '' . "\0" . 'Darkish\\CategoryBundle\\Entity\\News' . "\0" . 'createdDate', '' . "\0" . 'Darkish\\CategoryBundle\\Entity\\News' . "\0" . 'publishDate', '' . "\0" . 'Darkish\\CategoryBundle\\Entity\\News' . "\0" . 'expireDate', '' . "\0" . 'Darkish\\CategoryBundle\\Entity\\News' . "\0" . 'body', '' . "\0" . 'Darkish\\CategoryBundle\\Entity\\News' . "\0" . 'userId', '' . "\0" . 'Darkish\\CategoryBundle\\Entity\\News' . "\0" . 'status', '' . "\0" . 'Darkish\\CategoryBundle\\Entity\\News' . "\0" . 'isCompetition', '' . "\0" . 'Darkish\\CategoryBundle\\Entity\\News' . "\0" . 'trueAnswer', '' . "\0" . 'Darkish\\CategoryBundle\\Entity\\News' . "\0" . 'rate', '' . "\0" . 'Darkish\\CategoryBundle\\Entity\\News' . "\0" . 'category', '' . "\0" . 'Darkish\\CategoryBundle\\Entity\\News' . "\0" . 'newstreeId');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (News $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function validate(\Symfony\Component\Validator\ExecutionContextInterface $context)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'validate', array($context));

        return parent::validate($context);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitle($title)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitle', array($title));

        return parent::setTitle($title);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitle', array());

        return parent::getTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function setSubTitle($subTitle)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSubTitle', array($subTitle));

        return parent::setSubTitle($subTitle);
    }

    /**
     * {@inheritDoc}
     */
    public function getSubTitle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSubTitle', array());

        return parent::getSubTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedDate($createdDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedDate', array($createdDate));

        return parent::setCreatedDate($createdDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedDate', array());

        return parent::getCreatedDate();
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedDateObject()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedDateObject', array());

        return parent::getCreatedDateObject();
    }

    /**
     * {@inheritDoc}
     */
    public function setExpireDate($expireDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExpireDate', array($expireDate));

        return parent::setExpireDate($expireDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getExpireDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExpireDate', array());

        return parent::getExpireDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setBody($body)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBody', array($body));

        return parent::setBody($body);
    }

    /**
     * {@inheritDoc}
     */
    public function getBody()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBody', array());

        return parent::getBody();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserId($userId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserId', array($userId));

        return parent::setUserId($userId);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserId', array());

        return parent::getUserId();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', array($status));

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', array());

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsCompetition($isCompetition)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsCompetition', array($isCompetition));

        return parent::setIsCompetition($isCompetition);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsCompetition()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsCompetition', array());

        return parent::getIsCompetition();
    }

    /**
     * {@inheritDoc}
     */
    public function setTrueAnswer($trueAnswer)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTrueAnswer', array($trueAnswer));

        return parent::setTrueAnswer($trueAnswer);
    }

    /**
     * {@inheritDoc}
     */
    public function getTrueAnswer()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTrueAnswer', array());

        return parent::getTrueAnswer();
    }

    /**
     * {@inheritDoc}
     */
    public function setRate($rate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRate', array($rate));

        return parent::setRate($rate);
    }

    /**
     * {@inheritDoc}
     */
    public function getRate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRate', array());

        return parent::getRate();
    }

    /**
     * {@inheritDoc}
     */
    public function setCategory($category)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCategory', array($category));

        return parent::setCategory($category);
    }

    /**
     * {@inheritDoc}
     */
    public function getCategory()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategory', array());

        return parent::getCategory();
    }

    /**
     * {@inheritDoc}
     */
    public function setNewstreeId($newstreeId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNewstreeId', array($newstreeId));

        return parent::setNewstreeId($newstreeId);
    }

    /**
     * {@inheritDoc}
     */
    public function getNewstreeId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNewstreeId', array());

        return parent::getNewstreeId();
    }

    /**
     * {@inheritDoc}
     */
    public function setPublishDate($publishDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPublishDate', array($publishDate));

        return parent::setPublishDate($publishDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getPublishDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPublishDate', array());

        return parent::getPublishDate();
    }

}
