<?php

namespace Proxies\__CG__\Darkish\CategoryBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Offer extends \Darkish\CategoryBundle\Entity\Offer implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Darkish\\CategoryBundle\\Entity\\Offer' . "\0" . 'id', '' . "\0" . 'Darkish\\CategoryBundle\\Entity\\Offer' . "\0" . 'title', '' . "\0" . 'Darkish\\CategoryBundle\\Entity\\Offer' . "\0" . 'createdDate', '' . "\0" . 'Darkish\\CategoryBundle\\Entity\\Offer' . "\0" . 'publishDate', '' . "\0" . 'Darkish\\CategoryBundle\\Entity\\Offer' . "\0" . 'expireDate', '' . "\0" . 'Darkish\\CategoryBundle\\Entity\\Offer' . "\0" . 'body', '' . "\0" . 'Darkish\\CategoryBundle\\Entity\\Offer' . "\0" . 'userId', '' . "\0" . 'Darkish\\CategoryBundle\\Entity\\Offer' . "\0" . 'status', '' . "\0" . 'Darkish\\CategoryBundle\\Entity\\Offer' . "\0" . 'category', '' . "\0" . 'Darkish\\CategoryBundle\\Entity\\Offer' . "\0" . 'offertreeId', '' . "\0" . 'Darkish\\CategoryBundle\\Entity\\Offer' . "\0" . 'firstPhone', '' . "\0" . 'Darkish\\CategoryBundle\\Entity\\Offer' . "\0" . 'secondPhone', '' . "\0" . 'Darkish\\CategoryBundle\\Entity\\Offer' . "\0" . 'email', '' . "\0" . 'Darkish\\CategoryBundle\\Entity\\Offer' . "\0" . 'unitNumber', '' . "\0" . 'Darkish\\CategoryBundle\\Entity\\Offer' . "\0" . 'firstImage', '' . "\0" . 'Darkish\\CategoryBundle\\Entity\\Offer' . "\0" . 'secondImage', '' . "\0" . 'Darkish\\CategoryBundle\\Entity\\Offer' . "\0" . 'thirdImage', '' . "\0" . 'Darkish\\CategoryBundle\\Entity\\Offer' . "\0" . 'banner');
        }

        return array('__isInitialized__', '' . "\0" . 'Darkish\\CategoryBundle\\Entity\\Offer' . "\0" . 'id', '' . "\0" . 'Darkish\\CategoryBundle\\Entity\\Offer' . "\0" . 'title', '' . "\0" . 'Darkish\\CategoryBundle\\Entity\\Offer' . "\0" . 'createdDate', '' . "\0" . 'Darkish\\CategoryBundle\\Entity\\Offer' . "\0" . 'publishDate', '' . "\0" . 'Darkish\\CategoryBundle\\Entity\\Offer' . "\0" . 'expireDate', '' . "\0" . 'Darkish\\CategoryBundle\\Entity\\Offer' . "\0" . 'body', '' . "\0" . 'Darkish\\CategoryBundle\\Entity\\Offer' . "\0" . 'userId', '' . "\0" . 'Darkish\\CategoryBundle\\Entity\\Offer' . "\0" . 'status', '' . "\0" . 'Darkish\\CategoryBundle\\Entity\\Offer' . "\0" . 'category', '' . "\0" . 'Darkish\\CategoryBundle\\Entity\\Offer' . "\0" . 'offertreeId', '' . "\0" . 'Darkish\\CategoryBundle\\Entity\\Offer' . "\0" . 'firstPhone', '' . "\0" . 'Darkish\\CategoryBundle\\Entity\\Offer' . "\0" . 'secondPhone', '' . "\0" . 'Darkish\\CategoryBundle\\Entity\\Offer' . "\0" . 'email', '' . "\0" . 'Darkish\\CategoryBundle\\Entity\\Offer' . "\0" . 'unitNumber', '' . "\0" . 'Darkish\\CategoryBundle\\Entity\\Offer' . "\0" . 'firstImage', '' . "\0" . 'Darkish\\CategoryBundle\\Entity\\Offer' . "\0" . 'secondImage', '' . "\0" . 'Darkish\\CategoryBundle\\Entity\\Offer' . "\0" . 'thirdImage', '' . "\0" . 'Darkish\\CategoryBundle\\Entity\\Offer' . "\0" . 'banner');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Offer $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitle($title)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitle', array($title));

        return parent::setTitle($title);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitle', array());

        return parent::getTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedDate($createdDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedDate', array($createdDate));

        return parent::setCreatedDate($createdDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedDate', array());

        return parent::getCreatedDate();
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedDateObject()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedDateObject', array());

        return parent::getCreatedDateObject();
    }

    /**
     * {@inheritDoc}
     */
    public function setExpireDate($expireDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExpireDate', array($expireDate));

        return parent::setExpireDate($expireDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getExpireDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExpireDate', array());

        return parent::getExpireDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setBody($body)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBody', array($body));

        return parent::setBody($body);
    }

    /**
     * {@inheritDoc}
     */
    public function getBody()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBody', array());

        return parent::getBody();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserId($userId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserId', array($userId));

        return parent::setUserId($userId);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserId', array());

        return parent::getUserId();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', array($status));

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', array());

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setCategory($category)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCategory', array($category));

        return parent::setCategory($category);
    }

    /**
     * {@inheritDoc}
     */
    public function getCategory()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategory', array());

        return parent::getCategory();
    }

    /**
     * {@inheritDoc}
     */
    public function setOffertreeId($offertreeId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOffertreeId', array($offertreeId));

        return parent::setOffertreeId($offertreeId);
    }

    /**
     * {@inheritDoc}
     */
    public function getOffertreeId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOffertreeId', array());

        return parent::getOffertreeId();
    }

    /**
     * {@inheritDoc}
     */
    public function setPublishDate($publishDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPublishDate', array($publishDate));

        return parent::setPublishDate($publishDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getPublishDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPublishDate', array());

        return parent::getPublishDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setFirstPhone($firstPhone)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFirstPhone', array($firstPhone));

        return parent::setFirstPhone($firstPhone);
    }

    /**
     * {@inheritDoc}
     */
    public function getFirstPhone()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFirstPhone', array());

        return parent::getFirstPhone();
    }

    /**
     * {@inheritDoc}
     */
    public function setSecondPhone($secondPhone)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSecondPhone', array($secondPhone));

        return parent::setSecondPhone($secondPhone);
    }

    /**
     * {@inheritDoc}
     */
    public function getSecondPhone()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSecondPhone', array());

        return parent::getSecondPhone();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', array($email));

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', array());

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setUnitNumber($unitNumber)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUnitNumber', array($unitNumber));

        return parent::setUnitNumber($unitNumber);
    }

    /**
     * {@inheritDoc}
     */
    public function getUnitNumber()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUnitNumber', array());

        return parent::getUnitNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setFirstImage($firstImage)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFirstImage', array($firstImage));

        return parent::setFirstImage($firstImage);
    }

    /**
     * {@inheritDoc}
     */
    public function getFirstImage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFirstImage', array());

        return parent::getFirstImage();
    }

    /**
     * {@inheritDoc}
     */
    public function setSecondImage($secondImage)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSecondImage', array($secondImage));

        return parent::setSecondImage($secondImage);
    }

    /**
     * {@inheritDoc}
     */
    public function getSecondImage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSecondImage', array());

        return parent::getSecondImage();
    }

    /**
     * {@inheritDoc}
     */
    public function setThirdImage($thirdImage)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setThirdImage', array($thirdImage));

        return parent::setThirdImage($thirdImage);
    }

    /**
     * {@inheritDoc}
     */
    public function getThirdImage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getThirdImage', array());

        return parent::getThirdImage();
    }

    /**
     * {@inheritDoc}
     */
    public function setBanner($banner)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBanner', array($banner));

        return parent::setBanner($banner);
    }

    /**
     * {@inheritDoc}
     */
    public function getBanner()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBanner', array());

        return parent::getBanner();
    }

}
