services:
    customer.subscriber:
        class: Darkish\CustomerBundle\EventListener\CustomerSubscriber
        arguments:
            - @security.encoder_factory
        tags:
            - { name: doctrine.event_subscriber, connection: default }
    security.access.customer_voter:
        class:      Darkish\CustomerBundle\Security\Voter\CustomerVoter
        public:     false
        tags:
           - { name: security.voter }
    customer_authenticator:
        class:     Darkish\CustomerBundle\Security\Authenticator
        arguments: ["@security.encoder_factory"]

