services:
    customer.subscriber:
        class: Darkish\CustomerBundle\EventListener\CustomerSubscriber
        arguments:
            - @security.encoder_factory
        tags:
            - { name: doctrine.event_subscriber, connection: default }
    