services:
    security.access.post_voter:
        class:      Darkish\CategoryBundle\Security\Voter\PostVoter
        public:     false
        tags:
           - { name: security.voter }
    security.access.news_voter:
        class:      Darkish\CategoryBundle\Security\Voter\NewsVoter
        public:     false
        tags:
           - { name: security.voter }

parameters:
#    darkish_category.example.class: Darkish\CategoryBundle\Example

#services:
#    darkish_category.example:
#        class: %darkish_category.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

