services:
    security.access.post_voter:
        class:      Darkish\CategoryBundle\Security\Voter\PostVoter
        public:     false
        tags:
           - { name: security.voter }
    security.access.news_voter:
        class:      Darkish\CategoryBundle\Security\Voter\NewsVoter
        public:     false
        tags:
           - { name: security.voter }
    security.access.offer_voter:
        class:      Darkish\CategoryBundle\Security\Voter\OfferVoter
        public:     false
        tags:
           - { name: security.voter }
    security.access.sponsor_voter:
        class:      Darkish\CategoryBundle\Security\Voter\SponsorVoter
        public:     false
        tags:
           - { name: security.voter }
    security.access.classified_voter:
        class:      Darkish\CategoryBundle\Security\Voter\ClassifiedVoter
        public:     false
        tags:
           - { name: security.voter }
    app.menu_builder:
        class: Darkish\CategoryBundle\Menu\MenuBuilder
        arguments: ["@knp_menu.factory", "@security.context", "@service_container"]

    app.main_menu:
        class: Knp\Menu\MenuItem # the service definition requires setting the class
        factory_service: app.menu_builder
        factory_method: createMainMenu
        arguments: ["@request_stack"]
        tags:
            - { name: knp_menu.menu, alias: main } # The alias is what is used to retrieve the menu
    my_file.subscriber:
        class: Darkish\CategoryBundle\EventListener\FileSubscriber
        arguments: ["@service_container", "@request_stack"]
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    my_cnor.subscriber:
        class: Darkish\CategoryBundle\EventListener\CnorSubscriber
        arguments: ["@service_container", "@request_stack"]
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    message_thread.subscriber:
        class: Darkish\CategoryBundle\EventListener\MessageThreadSubscriber
        tags:
            - { name: doctrine.event_subscriber, connection: default }

parameters:
#    darkish_category.example.class: Darkish\CategoryBundle\Example

#services:
#    darkish_category.example:
#        class: %darkish_category.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

